id: 2a2d1c40-bee8-4e0a-9c07-d784776a6eb5
name: ProjectContext
type: c4-project
caepVersion: 6
description: This is a sample project configuration for C4 model generation.
children:
- id: 8f2d6017-0f26-49f2-a3e4-3caca1efa9bd
  type: software-system
- id: 8ff5cc13-0dc6-4acc-858c-6781d92dd8d3
  type: person
tenantId: 5f37364f-201e-47ea-2e89-08dd02619fda
